POST http://localhost:5000/api/users/signup
content-type: application/json

{ 

  "name": "Devanshh Shrivastvaaaa",
  "phoneNumber":"9829648888",
  "email": "devansh;@typ.in",
  "password": "1234566788" 
}

###

POST http://localhost:5000/api/users/login
content-type: application/json

{ 
  "email": "devansh;@typ.in",
  "password": "1234566788" 
}


###

POST  http://localhost:5000/api/movies/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjNmZGY1MDIxNmFhZjNlNTA4NjdmMTMiLCJlbWFpbCI6ImRldmFuc2g7QHR5cC5pbiIsImlhdCI6MTU5ODAyMjc2NCwiZXhwIjoxNTk4MDI2MzY0fQ.OLqrtDM9_3M-bOx5aLx4iMZxL32_8PBFuVpod6fcatU
content-type: application/json

{ 
  "userId":"5f3fdf50216aaf3e50867f13",
  "name":"Avengers: Endgame",
  "img":"https://bit.ly/2Pzczlb",
  "summary":"Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe."
}


###
GET http://localhost:5000/api/movies/allMovies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjNmZGY1MDIxNmFhZjNlNTA4NjdmMTMiLCJlbWFpbCI6ImRldmFuc2g7QHR5cC5pbiIsImlhdCI6MTU5ODAyMjc2NCwiZXhwIjoxNTk4MDI2MzY0fQ.OLqrtDM9_3M-bOx5aLx4iMZxL32_8PBFuVpod6fcatU


